[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
test = "tests"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin-contracts-upgradeable/contracts/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "boundless/=dependencies/boundless-1.1.1/contracts/src/",
    "forge-std/=dependencies/forge-std-1.9.5/src/",
    "openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "risc0/=dependencies/risc0-2.1.0/contracts/src/",
]

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.1.0"
risc0 = { version = "2.1.0", git = "https://github.com/risc0/risc0-ethereum.git", tag = "v2.1.0" }
boundless = { version = "1.1.1", git = "https://github.com/boundless-xyz/boundless", tag = "v1.1.1" }
"@openzeppelin-contracts-upgradeable" = "5.1.0"

[soldeer]
remappings_generate = true
remappings_version = false
remappings_location = "config"
